### ISSUE TITLE
Implement XML variant of module metadata

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-modularity/libmodulemd#101]
For various reasons, a number of tools and systems expect all of rpm-md to be XML formatted, and the current implementation of module metadata breaks this expectation.

In order to make it possible for the ecosystem at large to be able to handle module metadata properly, please implement support for generating and handling module metadata in XML instead of YAML. This restores the consistency for rpm-md repodata, and unblocks a number of opportunities to properly support the metadata extension in various consumers of rpm-md.

**Comment by sgallagher** [comment]
This isn't realistically going to happen in the 2.0 release. Moving to a 3.0 target in the indeterminate future so as to reflect reality.

I realize that this is a desirable feature for certain setups, OBS included, but unfortunately we don't have the cycles/humanpower to get it in on the schedule we need for 2.0.

**Comment by Conan-Kudo** [comment]
I've got some free cycles coming up soon, so if it would help, I can look at designing the XML metadata schema based on the current YAML form.

**Comment by Conan-Kudo** [comment]
In a F2F meeting, @ignatenkobrain has agreed to try to convince libsolv upstream to allow a libyaml dependency to support the native metadata format, which should obsolete the need for this.
