### ISSUE TITLE
How should the multilib work?

### ISSUE THREAD

**Issue by hanzz** [fedora-modularity/libmodulemd#12]
I'm going to implement proper multilib in Pungi, spec.v2.yaml says:

```
# A list of architectures with multilib
# installs, i.e. both i686 and x86_64
# versions will be installed on x86_64.
# TODO: This needs to be reworked or dropped as it's not at all useful in the current state.
# Optional, defaults to no multilib.
multilib: [ x86_64 ]
```

I talked with @contyk about this and he says the TODO basically means it is not clear what the arches should be in multilib field and if the current way how multilib field is defined is enough. We should have the final way how to define multilib so I can implement that in Pungi.

From the Pungi perspective, the current way with `multilib: [x86_64]` would be enough. It would work like this:

- When component has x86_64 multilib set in modulemd, the binary RPMs built from this component for x86_64 and also for other multilib arches would be considered for x86_64 compose.
- Depending on compose variant the Pungi's `multilib` strategy (see "multilib" [here](https://docs.pagure.org/pungi/configuration.html)) would really be the option defining whether the particular RPMs end up in compose or not. So it might be possible that component with "multilib" set in modulemd won't appear in resulting variant, because the `multilib` Pungi option will disallow that for particular variant.

**Comment by ignatenkobrain** [comment]
I don't think this field should be in there at all... or it should be simple true/false.

Another option is to set multilib per-component which probably would be best. Now you have to ask releng to tweak pungi configuration which means in modular world this won't be possible. So if we allow users to do per-component multilib -- would be awesome.

Getting back to value of multilib.. Having arch where we **do** multilib is probably useful too...

**Comment by hanzz** [comment]
> I don't think this field should be in there at all... or it should be simple true/false.

Which multilib field? The one in Pungi configuration or the one in Modulemd?

I'm confused, because the multilib field in modulemd yaml already is per component.

**Comment by ignatenkobrain** [comment]
@hanzz in both.

**Comment by contyk** [comment]
I updated the specification some time ago.

The spec already includes per component multilib fields and those list koji arches for which multilib should be enabled. What exactly that translates to depends on what we build, what's available and multilib rules in the composer. I think this can be closed.
