### ISSUE TITLE
module defaults should be versioned

### ISSUE THREAD

**Issue by kkaarreell** [fedora-modularity/libmodulemd#148]
Module defaults should be versioned so in case I have an older copy of Modular repository and there is possibly a conflict in defaults the newer definition is used.

**Comment by sgallagher** [comment]
@contyk, @whitel @asamalik  We've resisted this in the past because we'd been assuming that the defaults would not be changing except on major release upgrades, but I'm starting to see the value in it.

I think we could add a `modified` field into the `data` section like we have in the [Translation](https://github.com/fedora-modularity/libmodulemd/blob/master/translations/spec.v1.yaml#L14) documents and use that to cue the override logic in the merge process.

For backwards-compatibility, we could assume that an unset `modified` field is set to zero. In the event that we have two Defaults at the same level (such as zero), it would fall back to the current behavior of attempting to merge them or override them (if the repository was set thusly).

**Comment by whitel** [comment]
I think there is a whole host of reasons to carry a modified timestamp. I am definitely +1 and not sure why we didn't have this in the first place. 

I was thinking we could assume "blank" == "file modified date" from the server rather than 0. However, we should probably always assume the server may not be available and the filesystem date may not be reliable.

**Comment by sgallagher** [comment]
> I think there is a whole host of reasons to carry a modified timestamp. I am definitely +1 and not sure why we didn't have this in the first place.
> 
> I was thinking we could assume "blank" == "file modified date" from the server rather than 0. However, we should probably always assume the server may not be available and the filesystem date may not be reliable.

Additionally, libmodulemd wouldn't actually have access to that information without a major redesign (and one per year is enough for me, thank you). The contents of the metadata are retrieved by the program first and then passed to us. libmodulemd does not perform any direct activity with the repository.

**Comment by asamalik** [comment]
+1

**Comment by ignatenkobrain** [comment]
+1

**Comment by contyk** [comment]
So I'm generally +1 and I also think this doesn't require a format version bump if we assume that undefined = 0.

But before we move forward, could you describe your proposal of all the merge scenarios?

**Comment by sgallagher** [comment]
# Current

Merging Defaults entries behaves as follows:
- Any module default that is provided by a single repository is authoritative.
- If the repos have different priorities (not common), then the default for this module and stream name coming from the repo of higher priority will be used and the default from the lower-priority repo will not be included.
- If the repos have the same priority (such as "fedora" and "updates" in the Fedora Project), the entries will be merged as follows:
  - If both repositories specify a default stream for the module, use it.
  - If either repository specifies a default stream for the module and the other does not, use the one specified.
  - If both repositories specify different streams, this is an unresolvable merge conflict and the merge resolution will fail and report an error.
  - If both repositories specify a set of default profiles for a stream and the sets are equivalent, use that set.
  - If one repository specifies a set of default profiles for a stream and the other does not, use the one specified.
  - If both repositories specify a set of default profiles for a stream and each are providing a different set, this is an unresolvable merge conflict and the merge resolution will fail and report an error.

# Proposed
Differences marked in bold.

Merging Defaults entries behaves as follows:
- **Within a ModuleIndex, if two or more default entries reference the same module, the one with the highest `modified` field will be used and the others discarded.**
- **When merging ModuleIndexes, if two or more indexes contain Defaults for the same module, but different `modified` values, the one with the highest `modified` value will be used and the others discarded.**
- Any module default that is provided by a single repository is authoritative.
- If the repos have different priorities (not common), then the default for this module and stream name coming from the repo of higher priority will be used and the default from the lower-priority repo will not be included **even if it has a higher modified value [(1)](#link_1)**.
- If the repos have the same priority (such as "fedora" and "updates" in the Fedora Project) **and `modified` value**, the entries will be merged as follows:
  - If both repositories specify a default stream for the module, use it.
  - If either repository specifies a default stream for the module and the other does not, use the one specified.
  - If both repositories specify different streams, this is an unresolvable merge conflict and the merge resolution will fail and report an error.
  - If both repositories specify a set of default profiles for a stream and the sets are equivalent, use that set.
  - If one repository specifies a set of default profiles for a stream and the other does not, use the one specified.
  - If both repositories specify a set of default profiles for a stream and each are providing a different set, this is an unresolvable merge conflict and the merge resolution will fail and report an error.

# Glossary:
* ModuleIndex: a libmodulemd 2.0 API object representing the complete set of information parsed from a yum/dnf repository.

# Footnotes
<a name="link_1">(1)</a> This is backwards-compatible with the previous approach. The idea was that a module priority setting in the yum repo would allow the user to specify that this repo should always "win" in case of conflicts (such as a third-party repo that ships its own default for a module that is later added to Fedora or RHEL AppStream).

**Comment by sgallagher** [comment]
> # Footnotes
> (1) This is backwards-compatible with the previous approach. The idea was that a module priority setting in the yum repo would allow the user to specify that this repo should always "win" in case of conflicts (such as a third-party repo that ships its own default for a module that is later added to Fedora or RHEL AppStream).

To expand on this a bit, DNF uses this functionality to ensure that Defaults on the local disk in `/etc/dnf/modules.defaults.d/` will always supersede the contents in the repository. I don't want the `modified` value to interfere with that.

**Comment by contyk** [comment]
Thank you. +1.
