### ISSUE TITLE
Python segfaults when running `add_rpm_component`

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#15]
The following causes Python to segfault:
```python
>>> import gi
>>> gi.require_version('Modulemd', '1.0')
>>> from gi.repository import Modulemd
>>> mmd = Modulemd.Module().new_from_file('tests/staged_data/formatted_testmodule.yaml')
>>> component = Modulemd.ComponentRpm()
>>> component.set_name('test')
>>> mmd.add_rpm_component(component)
```

This is the modulemd I'm using:
https://pagure.io/fm-orchestrator/blob/master/f/tests/staged_data/formatted_testmodule.yaml

**Comment by mprahl** [comment]
Nevermind, I had a syntax error.

**Comment by sgallagher** [comment]
@mprahl Can you share the syntax error? A segfault should still not have happened...

**Comment by mprahl** [comment]
@sgallagher I had accidentally reassigned the value of `component.set_name` rather than running the function. It was a copy-paste error while I was working on migrating MBS to libmodulemd.
