### ISSUE TITLE
libmodulemd's strict checking behavior

### ISSUE THREAD

**Issue by contyk** [fedora-modularity/libmodulemd#161]
In order to be ready for any future metadata additions without requiring an up-to-date libmodulemd, the default strict format checking behavior should be changed.

In APIv2 this should be configurable, preferrably non-strict by default. CI and buildsystems could enable the strict mode explicitly to generate quality content. Most other tools should be fine with non-strict.

If possible, make this available in APIv1 as well. Considering this would be a backport and we'd like to avoid changes in that version, going with non-strict is be fine.

**Comment by sgallagher** [comment]
Fixed in 2.0.0beta2 (and the associated 1.8.0beta2)
