### ISSUE TITLE
[RFE] Remove warning on v1->v2 upgrade on modulemds that don't have `eol` set

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#17]
When upgrading a v1 modulemd to v2 that doesn't have the `eol` property set, you get the warning `__main__:1: Warning: g_date_valid: assertion 'd != NULL' failed`. This warning isn't useful since a v1 modulemd is valid without having the `eol` property set. It'd be friendlier to not have this warning, especially since it can pollute application logs if the `upgrade` function is often run.

Here is how to produce the warning message:

```python
>>> import gi
>>> gi.require_version('Modulemd', '1.0')
>>> from gi.repository import Modulemd
>>> mmd = Modulemd.Module().new_from_string('document: modulemd\nversion: 1\ndata:\n    summary: A test module in all its beautiful beauty\n    description: >-\n        This module demonstrates how to write simple modulemd files And\n        can be used for testing the build and release pipeline.\n    license:\n        module: [ MIT ]\n    dependencies:\n        buildrequires:\n            platform: f28\n        requires:\n            platform: f28\n    references:\n        community: https://docs.pagure.org/modularity/\n        documentation: https://fedoraproject.org/wiki/Fedora_Packaging_Guidelines_for_Modules\n    profiles:\n        default:\n            rpms:\n            - tangerine\n    api:\n        rpms:\n        - perl-Tangerine\n        - tangerine\n    components:\n        rpms:\n            perl-List-Compare:\n                rationale: A dependency of tangerine.\n                ref: master\n            perl-Tangerine:\n                rationale: Provides API for this module and is a dependency of tangerine.\n                ref: master\n            tangerine:\n                rationale: Provides API for this module.\n                buildorder: 10\n                ref: master\n')
>>> mmd.upgrade()
__main__:1: Warning: g_date_valid: assertion 'd != NULL' failed
True
```

**Comment by ignatenkobrain** [comment]
Yeah, I wanted to talk with @sgallagher about this once he gets back ;)

**Comment by sgallagher** [comment]
I ended up fixing this issue incidentally as part of a rework of the solution for https://github.com/fedora-modularity/libmodulemd/issues/18 in https://github.com/fedora-modularity/libmodulemd/commit/2b12f6af57b9db0e3a0de9d0b49e431d1b36abcd

The decision was to always return NULL on `get_eol()` if it is either unset or invalid. That way, the consumer doesn't have to handle both cases.
