### ISSUE TITLE
`new_from_file` and `new_from_string` hang indefinitely on bad YAML

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#18]
When trying to create a `Moduemd.Module` object with bad YAML, it will hang as long as the bad YAML starts with `document: modulemd\n`.

For example:
```python
from gi.repository import Modulemd
Modulemd.Module().new_from_string('document: modulemd\nBad YAML')
```

We need libmodulemd to be able fail on bad modulemd files that users submit to MBS.

**Comment by sgallagher** [comment]
Confirmed. I think I see where the problem is; I should have a fix in a couple hours.
