### ISSUE TITLE
Return `unicode` in `mmd.dumps()` with python2

### ISSUE THREAD

**Issue by hanzz** [fedora-modularity/libmodulemd#184]
The `dumps()` method currently returns `str` with py2, but the returned string can contain unicode characters. There is a way to convert it to unicode(string, "utf-8"), but it seems it is hard to do that nicely in a way that both python2 and python3 are supported.

Could instead the `dumps()` return unicode on Python2?

**Comment by sgallagher** [comment]
The situation here is that these strings are getting passed back via GObject Introspection bindings which, as far as I can tell, will only give you a UTF8-encoded 8-bit `str` type on Python 2. On Python 3 it will give you the Python 3 `str` type which is unicode-aware.

While I *could* offer you a hack for this specific function to decode it to `unicode`, it would still be `str` for functions like `ModuleStream.get_description()`. I really don't want to make such a change anywhere.

Wouldn't it be simpler to write a library function like:

```python
class HelperUtils
    def u(gi_str):
        if six.PY2:
            return gi_str.decode('utf-8')
        return gi_str
```

And then call:
```python
from HelperUtils import u
u(Modulemd.ModuleStream.dumps())
```
