### ISSUE TITLE
Provide method which compares two Defaults objects

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#187]
This should be a fairly easy (but not quick) addition to the 2.0 API. What we'll need:

Modulemd.Defaults (the parent class) will add a .equals() virtual function that will be implemented by Modulemd.DefaultsV1. Its responsibility will be to recurse down into the various objects and variables making up the Defaults and perform an equality comparison on them. If any of them are different, it should return false.

As an implementation recommendation, the child objects should "chain up" to the parent class to compare the pieces common to all.

**Comment by nfatma** [comment]
Hello!
I am an Outreachy applicant, I would like to work on this issue.

**Comment by sgallagher** [comment]
Please go right ahead!

I've also just added a new section to the README.md to help you get started setting up your development environment. Please let me know if you have any difficulty with getting started.

**Comment by OrionStar25** [comment]
> As an implementation recommendation, the child objects should "chain up" to the parent class to compare the pieces common to all.

Can you please explain what this means?

**Comment by sgallagher** [comment]
@OrionStar25 Sure! What it means is that for objects that are derived from other objects (such as the `Modulemd.DefaultsV1` object being derived from `Modulemd.Defaults`), it's best to have common code stored with the parent object.

In this case, it means that for attributes like "module_name", "mdversion" and "modified", the comparison should be done in a routine in `Modulemd.Defaults`, while comparisons of "default_stream" and profile data should be done in the `Modulemd.DefaultsV1` object.

For example, see https://github.com/fedora-modularity/libmodulemd/blob/master/modulemd/v2/modulemd-module-stream-v2.c#L764 for how we "chain up" in the `Modulemd.ModuleStreamV2.validate()` routine. It calls up to `Modulemd.ModuleStream.validate()` to verify the bits that are common to all `Modulemd.ModuleStream` objects and then proceeds further to validate the bits that are specific to `Modulemd.ModuleStreamV2`.

Let me know if that helps or if you need more guidance here.

**Comment by OrionStar25** [comment]
Thats enough to help me start! I'll open a PR soon
