### ISSUE TITLE
Enhance IndexMerger to use equality checks

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#188]
Right now, we use a highly-simplified comparison when merging ModuleStream objects from two different repositories. We check whether they have the same NSVC and then assume them to be the same content. It would be better to perform a full equality check.

This depends on https://github.com/fedora-modularity/libmodulemd/issues/186

**Comment by irenge** [comment]
Hi 
May I work on this issue ?
Thanks

**Comment by sgallagher** [comment]
@irenge Please go ahead.

**Comment by athira-selvam** [comment]
Hi @irenge are you working on this issue?

**Comment by irenge** [comment]
haha ! I thought the issue was closed . I am going back to it . R u interested in it ?

**Comment by sgallagher** [comment]
This isn't eligible to be worked on until #186 is merged. That issue needs to be resolved first.

**Comment by athira-selvam** [comment]
@sgallagher Hi, All beginner issues have been claimed. Is it okay to work on those issues? I have already copied tests for the depends_on_stream function to C. And I added a test for an empty stream. But that was in python. Can I work on copying that test to C and also copying some more functions from modulestream.py to C?
Can I work on -  [199](https://github.com/fedora-modularity/libmodulemd/issues/199 )or [198](https://github.com/fedora-modularity/libmodulemd/issues/198)
Or can you assign me something else to  work on

**Comment by sgallagher** [comment]
@athira-selvam If there isn't a specific issue available (and I don't have a spare moment today to try to come up with some new ones), my recommendation would be to look through the existing tests in the `v2` subdirectory, look at some edge-cases that aren't exercised there and submit some new tests.
