### ISSUE TITLE
Create Python tutorial: Getting the default stream for a module

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#189]
Currently, the README.md and [modulemd.h](https://github.com/fedora-modularity/libmodulemd/blob/master/modulemd/v2/include/modulemd-2.0/modulemd.h) files have some limited guides for how to work with libmodulemd, but some real tutorials on API 2.0 would be ideal.

Create tutorial documentation (either extending modulemd.h annotations or by adding a new Tutorial section to the documentation) describing the following process with code examples:

* Import the libmodulemd 2.0 API into a Python script
* Import repodata YAML from a file
* Query the `Modulemd.ModuleIndex` for the module with a given name
* Query the `Modulemd.Module` for the default stream.

**Comment by OrionStar25** [comment]
Can I work on this issue?

**Comment by nikitaa30** [comment]
I would like to know if I could contribute to this issue. Kindly guide me towards the same.

**Comment by sgallagher** [comment]
Either or both of you may work on this issue. Given that it is documentation, I'd expect that before it gets merged upstream, we'll end up combining the best parts of each of your submissions.
