### ISSUE TITLE
Create C tutorial: Getting the default stream for a module

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#190]
Currently, the README.md and [modulemd.h](https://github.com/fedora-modularity/libmodulemd/blob/master/modulemd/v2/include/modulemd-2.0/modulemd.h) files have some limited guides for how to work with libmodulemd, but some real tutorials on API 2.0 would be ideal.

Create tutorial documentation (either extending modulemd.h annotations or by adding a new Tutorial section to the documentation) describing the following process with examples:

* Include the appropriate C headers
* Read repodata YAML from a file into an index
* Query the `Modulemd.ModuleIndex` for the module with a given name
* Query the `Modulemd.Module` for the default stream.

**Comment by OrionStar25** [comment]
Can I work on this issue?  I'm applying for Outreachy

**Comment by sgallagher** [comment]
Please go right ahead!

I've also just added a new section to the README.md to help you get started setting up your development environment. Please let me know if you have any difficulty with getting started.

**Comment by irenge** [comment]
Can two people work on the same issue ?

**Comment by sgallagher** [comment]
@irenge I don't have a problem if you and @OrionStar25 each work on this issue separately, but please be aware that I will probably end up reviewing them individually and then asking the two of you to combine them together before I merge it upstream.
