### ISSUE TITLE
Create Python tutorial: List the RPM API for a provided module NSVC 

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#191]
Currently, the README.md and [modulemd.h](https://github.com/fedora-modularity/libmodulemd/blob/master/modulemd/v2/include/modulemd-2.0/modulemd.h) files have some limited guides for how to work with libmodulemd, but some real tutorials on API 2.0 would be ideal.

Create tutorial documentation (either extending modulemd.h annotations or by adding a new Tutorial section to the documentation) describing the following process with examples:

* Import the libmodulemd 2.0 API into a Python script
* Read repodata YAML from a file into an index
* Query the `Modulemd.ModuleIndex` for the module with a given name
* Query the `Modulemd.Module` for the `Modulemd.ModuleStream` associated with the provided NSVC (name-stream-version-context identifier).
* Read the RPM API from the `Modulemd.ModuleStream`

**Comment by ananyaarun** [comment]
@sgallagher May i work on this issue ?

**Comment by sgallagher** [comment]
Please go right ahead!

I've also just added a new section to the README.md to help you get started setting up your development environment. Please let me know if you have any difficulty with getting started.

**Comment by ananyaarun** [comment]
Sure , I will get started with setting up my development environment :)

**Comment by ananyaarun** [comment]
@sgallagher , I am done with the setup environment and reading the documentation. I had a question , i see in readme that 2 repos are being used to load and merge the metadata (fedora and updates). Should i continue with the assumption of this ? Also Regarding point 3 and 4 , does query mean adding code to documentation that inputs and searches for a given module ?

**Comment by sgallagher** [comment]
@ananyaarun For the purposes of this ticket, you can assume that you need to deal with only a single repo source.

Yes, what I mean is that the tutorial documentation should include source code examples of the exact commands that would be used to retrieve that information.
