### ISSUE TITLE
Extend tests for ModuleStream.depends_on_stream() to cover empty stream lists

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#192]
The tests for `depends_on_stream()` and `build_depends_on_stream()` should validate that it handles the case of an empty list of streams properly.

As per the specification, the behavior here must be that an empty list means "all possible values".

**Comment by athira-selvam** [comment]
Hi,
I am an Outreachy applicant, I would like to work on this project. Shall work on this issue?
 - Thank you.

**Comment by sgallagher** [comment]
Please go right ahead!

I've also just added a new section to the README.md to help you get started setting up your development environment. Please let me know if you have any difficulty with getting started.

**Comment by athira-selvam** [comment]
Hi,
I did set up the development environment. I need some help. Is modulestream.py -  the file that I have to add the tests to?  I found some tests for `depends_on_stream()` and `build_depends_on_stream()` in that file. Just wanted confirmation before I proceed.

**Comment by sgallagher** [comment]
> Hi,
> I did set up the development environment. I need some help. Is modulestream.py - the file that I have to add the tests to? I found some tests for `depends_on_stream()` and `build_depends_on_stream()` in that file. Just wanted confirmation before I proceed.

Yes, those are the tests I meant. You can choose to write them in either the Python tests or into new C tests in [modulemd/v2/tests/test-modulemd-modulestream.c](https://github.com/fedora-modularity/libmodulemd/blob/master/modulemd/v2/tests/test-modulemd-modulestream.c) (related: #199)
