### ISSUE TITLE
Add Mageia 7 tests

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-modularity/libmodulemd#195]
Since DNF 4.x landed in Mageia 7 (which is in Beta currently), libmodulemd is now present in this distribution.

We should make sure we don't accidentally break building and using the library on this distribution.

**Comment by sgallagher** [comment]
This would be a good task for an Outreachy candidate. To get started, take a look at the `.travis.yml` and `.travis/` directory in the source tree.

A new `.travis/mageia/` subdirectory should be created and populated with an appropriate Dockerfile and `travis-tasks.sh`.

**Comment by Conan-Kudo** [comment]
Note that `dnf` is present in Mageia containers since Mageia 6, so potentially the Fedora steps will work (with small modifications).

**Comment by johnsanc** [comment]
Hello,
I am an Outreachy candidate and would like to work on this issue!

**Comment by Lashuk1729** [comment]
Hello, I would like to ask, about the repository in travis-mageia.sh file. I'm having a issue finding the repository for mageia. I would appreciate it, if some information is given about it.

**Comment by sgallagher** [comment]
@Lashuk1729 If you cannot find a distro-specific repository, it's fine to use registry.docker.com

**Comment by Lashuk1729** [comment]
@sgallagher, thanks for the reply.

**Comment by Victory17** [comment]
Hi, is this issue already being worked on? If not I would like to take it up. 
I am an Outreachy applicant for this round.

**Comment by Lashuk1729** [comment]
@Victory17, I'm already working on this!

**Comment by athira-selvam** [comment]
@Lashuk1729 are you working on this?
