### ISSUE TITLE
Add openSUSE Tumbleweed tests

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#196]
Since DNF 4.x landed in openSUSE Leap 15.1 (which is in Beta currently) and openSUSE Tumbleweed, libmodulemd is now present in both distributions.

We should make sure we don't accidentally break building and using the library on those distributions (and prevent more issues like #177 or #180 from happening again).

**Comment by sgallagher** [comment]
This would be a good task for an Outreachy candidate. To get started, take a look at the `.travis.yml` and `.travis/` directory in the source tree.

A new `.travis/opensuse/` subdirectory should be created and populated with an appropriate Dockerfile and `travis-tasks.sh`.

**Comment by mariana-escobedo** [comment]
Hi Stephen, my name is Mariana, and I am an Outreach applicant this year and 
I am interested in contributing to fix this issue. 
I understand a new sub directory is needed containing travis-tasks.sh, and a Dockerfile. My only question is, where can I find the appropriate Dockerfile to include? 

This is my very first time contributing, so I apologize in advance if it might be an obvious question.

**Comment by sgallagher** [comment]
So, there is no pre-existing Dockerfile. You're going to need to look at how we run the tests for the other distributions (Fedora and CentOS) and construct a Dockerfile for use with OpenSUSE Tumbleweed.

@Conan-Kudo has offered to help you figure out what packages you will need there, so if you need specifics, please post your questions on this issue while @mentioning him (Typing his username with an @ in front of it) and he'll be sure to see it.

**Comment by susiejojo** [comment]
Hello, my name is Dipanwita. I am an Outreachy applicant and am interested in contributing to this project. But I am facing similar difficulty as @mariana-escobedo and would like some help from @sgallagher and @Conan-Kudo in constructing the Dockerfile. Thanks in advance.

**Comment by mariana-escobedo** [comment]
@Conan-Kudo Thank you for volunteering your help! I looked over the .tmpl and deps.tmpl files in both fedora and CentOS folders and I can see a general template to use. Where can I find the specific packages to include? 
If you have a preferred way of messaging please let me know as I am willing to work in a way thats convenient to you.

**Comment by sgallagher** [comment]
This was merged in https://github.com/fedora-modularity/libmodulemd/pull/220
