### ISSUE TITLE
ninja: error: loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by vatsalanarang** [fedora-modularity/libmodulemd#207]
I have ninja version 1.8.2 in my fedora environment.@sgallagher could you please tell me which ninja version this project is using.

**Comment by sgallagher** [comment]
This message indicates that you didn't execute `ninja` in a directory created by `meson`.

Please follow the instructions at https://github.com/fedora-modularity/libmodulemd/blob/master/README.md#building-the-sources
