### ISSUE TITLE
RFE: Support directly reading in compressed yaml streams (gzip, bz2, xz, zck,...)

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-modularity/libmodulemd#208]
In most cases, the module metadata is stored in a compressed form (with some kind of compression algorithm like gzip, bz2, xz, zck, etc.). As far as libmodulemd is concerned, it can't deal with these files directly.

It would be nice to be able to handle these files directly. This is likely better as a new function as to not break API expectations or ABI.

**Comment by NishkaDG** [comment]
May I work on this?

**Comment by sgallagher** [comment]
If you want to prepare a proposal for how to implement this, go ahead. Please don’t start writing any code; it’s a big task and needs significant design work first.

**Comment by sgallagher** [comment]
OK, looks like I'm going to need to implement at least part of this to work with `createrepo_c`/`mergerepo_c`.

What I plan to do is add a new function, `modulemd_module_index_update_from_custom()` that will take a function pointer to a custom `read()` function of the type [`yaml_read_handler_t`](https://github.com/yaml/libyaml/blob/master/include/yaml.h#L970) that will be passed directly to [`yaml_parser_set_input()`](https://github.com/yaml/libyaml/blob/master/include/yaml.h#L1369) and will then proceed as normal.

In the specific case of createrepo_c, this will mean wrapping the `cr_read()` function that handles the various compression formats into a `yaml_read_handler_t` function.

@Conan-Kudo Do you think this will be sufficient from the libmodulemd side? I don't really think libmodulemd needs to implement the compression-handling logic as long as the consumer can provide it with a valid stream of data.

**Comment by Conan-Kudo** [comment]
Honestly, the reason I think it should have it is because it is often the preferred way to store the metadata because it is huge otherwise.

If you don't think this is an issue, then I guess it isn't needed...

**Comment by sgallagher** [comment]
@Conan-Kudo I think I'd prefer to avoid adding all of the codec dependencies to libmodulemd itself, to keep things neat. That said, maybe we could look into adding a helper library (libmodulemd-codecs?) that a consumer could optionally link against.

The thing is, I suspect that the majority of consumers will need to have their own logic for accessing compressed content and it would be best in general if we just allowed them to pass this to us as a custom read handler.

Now, one thing I hadn't considered yesterday is what to do about python... we can't pass a function pointer or FILE * from python into the PyGObject bindings, so I guess having `ModulemdIndex.update_from_xz_file()` and `ModulemdIndex.update_from_xz_bytes()` might be our only option there.

What do you think about a supplementary library vs. a plugin architecture for libmodulemd?

**Comment by Conan-Kudo** [comment]
@sgallagher I think an extra library that offers those supplementary functions is fine, but that would make things complicated for bindings, wouldn't it?

Also note that modules are going to be zck-compressed in Fedora with Fedora 30 onward.

**Comment by sgallagher** [comment]
Right, the `xz` was meant to be an example. I'm not sure it would be too difficult for bindings. Instead of `index.update_from_file('filename')`, they'd have to call `ModulemdCodec.update_from_zck_file(index, 'filename')`. This could even be simplified in the GObject overrides to make it part of the `ModulemdIndex` object if we really wanted to.

But maybe it *would* be better to just have it be part of `ModulemdIndex` natively and lazy-load the required codec library the first time that function is called.

**Comment by sgallagher** [comment]
I'm reconsidering my stance on this; I was trying to avoid pulling in more dependencies, but I suppose as long as we restrict ourselves to supporting whatever is required by libsolvext.so in the same release, it's not like we'll be causing new deps to appear.

It probably means coordinating with libsolv to make sure that we enable the same algorithms at the same time, though. (For example, libzstd is not available on RHEL 8.0, but is supported by libsolv on Fedora 30).

**Comment by sgallagher** [comment]
We should probably implement this by way of GInputStream for flexibility.
