### ISSUE TITLE
Add support for removing modules from the ModuleIndex

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#209]
When dealing with repository creation, we need to be able to remove entire modules from the Index.

**Comment by ignatenkobrain** [comment]
Not necessarily :) for example, there are no "remove" methods in libsolv :D

**Comment by sgallagher** [comment]
We are talking about repo creation, not libsolv actions. Specifically, if I want to merge two repos, I may want to explicitly exclude a module that I know conflicts.
