### ISSUE TITLE
Provide Modulemd.Component.equals() method

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#215]
Implement an equality check for `Modulemd.Component` objects (and their child-classes, `Modulemd.ComponentModule` and `Modulemd.ComponentRpm`). This is necessary to implement #186.

**Comment by indigoOmega021** [comment]
Could I please be assigned this issue?

**Comment by sgallagher** [comment]
@indigoOmega021 Done.

Be aware that this one is slightly more complicated than the Profile or Buildopts one, as the equals() method needs to be added to the parent class and implemented in both child classes.

Good luck! Let me know if you need any help.

**Comment by OrionStar25** [comment]
@indigoOmega021 are you currently working on this?

**Comment by indigoOmega021** [comment]
@OrionStar25 yes.
