### ISSUE TITLE
Provide Modulemd.Dependencies.equals() method

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#216]
In order to implement #186, we need to be able to compare two `Modulemd.Dependencies` objects for equality.

**Comment by AarushiSingh09** [comment]
Hello!
Can I work on this issue?

**Comment by athira-selvam** [comment]
@AarushiSingh09 Are you working on this?

**Comment by Victory17** [comment]
Hi, I am an Outreachy participant for this round. Can I take up this issue, in case nobody is working on it?

**Comment by yashpupneja** [comment]
Hi I am an Outreachy participant . Can I work on this issue?

**Comment by AarushiSingh09** [comment]
Yes I am working on this issue.
