### ISSUE TITLE
Provide Modulemd.ServiceLevel.equals() method

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#218]
In order to implement #186, we need to have an equality function for `Modulemd.ServiceLevel` objects.

**Comment by divyabaid16** [comment]
Could I please be assigned this issue?

**Comment by sgallagher** [comment]
Go ahead! Sorry, I missed the notification of this.

**Comment by OrionStar25** [comment]
I'll work on this if its @divyabaid16 isn't working on this?
