### ISSUE TITLE
Eliminate typecasting warning for modulemd_hash_table_equals()

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#243]
https://github.com/fedora-modularity/libmodulemd/pull/213 introduced a warning when passing `modulemd_hash_table_sets_are_equal()` as an argument to `modulemd_hash_table_equals()` because the latter expects a `(void *, void *)` argument and `modulemd_hash_table_sets_are_equal()` accepts `(GHashTable *, GHashTable *).

The solution here is to add a new function to wrap `modulemd_hash_table_sets_are_equal()` and cast the `(void *)` pointers explicitly to `(GHashTable *)` pointers.

**Comment by OrionStar25** [comment]
What should I name the function and what file should I put it in?
