### ISSUE TITLE
libmodulemd-2.2.2 fails to build in environments without python2

### ISSUE THREAD

**Issue by larchunix** [fedora-modularity/libmodulemd#257]
Greetings,

Since b86732a, libmodulemd fails to build in environments without python2:

```
meson.build:70:0: ERROR:  <ExternalProgram 'python' -> ['/usr/bin/python']> is not a valid python
```

Installing python2 in the build environment "solves" the issue.

Regards,

**Comment by sgallagher** [comment]
It is required in order for the build to produce a GObject Introspection Override file for use with Python 2 bindings.

I can look into making this non-fatal, however, and just warn that the python 2 overrides will be unavailable.

**Comment by larchunix** [comment]
> I can look into making this non-fatal, however, and just warn that the python 2 overrides will be unavailable.

That would be great since python2 is reaching EOL next year.

**Comment by sgallagher** [comment]
> > I can look into making this non-fatal, however, and just warn that the python 2 overrides will be unavailable.
> 
> That would be great since python2 is reaching EOL next year.

I'm aware of that, but libmodulemd also needs to work with RHEL 7, which is python2-only and has support until at least June 2024.

What I will probably do is add a config option for `-Dpy2_override_path=<path>` and `-Dpy3_override_path=<path>`. If `-Dpy2_override_path=<path>` is specified, the dependency on python2 will be skipped.

**Comment by sgallagher** [comment]
I changed my mind. It doesn't make any sense to add the `pyN_override_path` arguments. I will just modify the `pymod.find_installation()` call to be non-fatal if `-Dwith_py2_overrides` was passed.

**Comment by sgallagher** [comment]
@larchunix Would you mind reviewing #258 for me?
