### ISSUE TITLE
dnf without modules support

### ISSUE THREAD

**Issue by kloczek** [fedora-modularity/libmodulemd#264]
Is it possible to build dnf without modules support?

**Comment by sgallagher** [comment]
This is the wrong place to ask that question. Try the DNF project.

That said, while you might be able to build it without module support, the result would simply not work properly with any repo combination that includes module metadata, so why exactly would you want to?

**Comment by Conan-Kudo** [comment]
@kloczek Please see https://github.com/rpm-software-management/libdnf/issues/641 for the RFE on building DNF without modularity support.
