### ISSUE TITLE
Redefine default branch for ref:

### ISSUE THREAD

**Issue by voxik** [fedora-modularity/libmodulemd#269]
The `ref:` [[1]] is defined as follows:

~~~
# Use this specific commit hash, branch name or tag for
# the build.  If ref is a branch name, the branch HEAD
# will be used.  If no ref is given, the master branch
# is assumed.
~~~

However to choose "master" as a default is completely wrong. This does not work and this does not work especially in RHEL, where there are used maintenance branches. Let me explain.

In RHEL, it is quite common to maintain version specific branches, e.g. rhel-8.0.0, rhel-8.1.0, etc. Lets say I have module `foo`, which refers to some other module, e.g.:

~~~
... snip ...

    components:
        # SRPMs
        rpms:
            bar:
                rationale: Dependnecy.
                ref: stream-foo-8.0.0

... snip ...
~~~

Now with the move to RHEL 8.1.0 development, I would need to change the module file every time? That does not make any sense. It is fragile and error prone. This must be changed IMO.

The default `ref:` should be based on the name of the module branch. I.e. the `foo` module hast to have `foo-8.0.0` branch, the component has to have `stream-foo-8.0.0` branch and if these branches exists, they must be preferred over master.

Please note that this also relates to suggested branching model and to this discussion [[2]].

[1]: https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml#L268
[2]: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/4T4CIQENRHJ5F4DD2O6NWYAWFIYB5D2V/

**Comment by voxik** [comment]
Actually, there rule should be simpler. Whatever the name of the branch is in module repository, the same branch must be used for the referred components. If there is not branch like this for the specified component, then master is used.

**Comment by sgallagher** [comment]
@voxik: Could you please move this to the [MBS tracker](https://pagure.io/fm-orchestrator/) instead of the libmodulemd one? I realize that we keep the specification here, but libmodulemd doesn't actually do anything with the `ref` field directly, other than to confirm that it's a scalar value (and not a list or map). How it is interpreted for builds is done entirely on the MBS side. It seems like a reasonable request, and if it's agreed on for MBS, I'll update the specification here.

**Comment by voxik** [comment]
Done:

https://pagure.io/fm-orchestrator/issue/1226

I think we should still keep this open to update the specification.

**Comment by mprahl** [comment]
@sgallagher and @voxik, an alternative is to change the ref based on the buildrequired platform. One option could be to have the ability to use "variables" in the modulemd spec. For instance, based on the example in the initial post, the syntax could be something like:
```
... snip ...
  dependencies:
  - buildrequires:
      platform:
      - el8.1.0
... snip ...
  components:
    # SRPMs
    rpms:
      bar:
        rationale: Dependnecy.
        ref: 'stream-foo-${buildrequire.platform.stream}'
... snip ...
```

Then MBS would perform the replacement at submission time. The problem is that the ref would be `stream-foo-el8.1.0` instead of `stream-foo-8.1.0` which would require a minor change in branch names.

My preference towards a solution like this is that it's explicit by the packager, and the current behavior remains the same.

**Comment by voxik** [comment]
> One option could be to have the ability to use "variables" in the modulemd spec.

Please no. Instead of on convention, which helps to understand the relation between the module and component from both directions, you are adding one more degree of freedom. That is not what I want.

Moreover, it does not fix my initial concern, that is to avoid the need of module modification due to versioned branches.

**Comment by voxik** [comment]
> helps to understand the relation between the module and component from both directions

And really, if you check \[[1]\], you could see that the freedom which is currently given by the ref is actually big design flaw, because it makes things nontransparent and in the end even less flexible (as I mentioned here \[[2]\]), because you basically consider just the scenario that one module refers to N components, but you don't consider the scenario where one component is referenced by N modules.


[1]: https://pagure.io/jaruga-modules-branches
[2]: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/PMIDC6LVJ7YVOM6EPTV4LE4FFIRS5SU4/

**Comment by mprahl** [comment]
@voxik, adding this capability in MBS is not difficult, but Release Engineering would have to determine if this is the desired work flow. That is not something I control. If Release Engineering decides this is the path to take, we can prioritize this change accordingly.

**Comment by voxik** [comment]
> If Release Engineering decides this is the path to take, we can prioritize this change accordingly.

I don't think this has anything to do with release engineering. Everybody is free to use this branching model right now. What I am proposing is updated default, so there is more convention instead of configuration.

**Comment by sgallagher** [comment]
> > If Release Engineering decides this is the path to take, we can prioritize this change accordingly.
> 
> I don't think this has anything to do with release engineering. Everybody is free to use this branching model right now. What I am proposing is updated default, so there is more convention instead of configuration.

@voxik 
What @mprahl means is that it's not up to him to decide if the proposed workflow is the correct one. From the conversation in https://pagure.io/fm-orchestrator/issue/1226 it sounds like there are flaws in this requested approach. So we are not going to implement this way of doing it.

**Comment by mprahl** [comment]
> > If Release Engineering decides this is the path to take, we can prioritize this change accordingly.
> 
> I don't think this has anything to do with release engineering. Everybody is free to use this branching model right now. What I am proposing is updated default, so there is more convention instead of configuration.

It does because Release Engineering internally defines the branch naming conventions.

**Comment by voxik** [comment]
This proposal is not against branch naming conventions defined by RCM not for Fedora (there are not policies at all) neither internally (RCM dictates "stream-" prefix for components, but as far as I know, there is no real restriction on module branches. They could have the same "stream-" prefix).
