### ISSUE TITLE
get_xmd causes an assertion error when called twice

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#274]
When using `get_xmd` on a modulemd file from Python twice in a row, an assertion error is raised and it causes Python to crash. Here is the reproducer:
```python
import requests
import gi
gi.require_version("Modulemd", "2.0")
from gi.repository import Modulemd

mmd_str = requests.get(
    'https://pagure.io/fm-orchestrator/raw/master/f/tests/staged_data/platform.yaml').text
mmd = Modulemd.ModuleStream.read_string(mmd_str, True)
mmd.get_xmd()['mbs']
mmd.get_xmd()['mbs']
```

Here is the output when I run the reproducer:
```
(devenv) [vagrant@localhost module_build_service]$ python reproducer.py 
reproducer.py:10: Warning: g_variant_ref_sink: assertion 'value->ref_count > 0' failed
  mmd.get_xmd()['mbs']
**
GLib:ERROR:gvarianttypeinfo.c:184:g_variant_type_info_check: assertion failed: (0 <= index && index < 24)
Aborted (core dumped)
```

**Comment by sgallagher** [comment]
@mprahl I think I've got this figured out. I'm scratch-building a patched version at https://koji.fedoraproject.org/koji/taskinfo?taskID=34555011 for F29.

If you could pull that and verify that it resolves things for you (and unblocks you), I'd appreciate it.

**Comment by sgallagher** [comment]
@mprahl That scratch-build was missing one of the test data files. https://koji.fedoraproject.org/koji/taskinfo?taskID=34558963 should work properly.

**Comment by mprahl** [comment]
@sgallagher the scratch build works as expected. Thanks!
