### ISSUE TITLE
Add the ability to remove entries from the dependencies array

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#286]
MBS currently uses libmodulemd v1. As part of module stream expansion, MBS creates a copy of the source `Module` object, and runs `set_dependencies((new_dep, ))` with the resulting dependency combination. This is repeated for every dependency combination.

In other parts of the code, MBS also modifies the dependency objects directly with things such as `deps.set_requires(expanded)`.

As part of the migration to libmodulde v2, MBS needs the ability to remove `Modulemd.Dependencies` objects from the dependencies array. This can be clearing all existing dependencies, or removing a single dependency entry at a time. Although the latter is preferred, the former would also work.

**Comment by sgallagher** [comment]
Scratch-build with the referenced PR applied: https://koji.fedoraproject.org/koji/taskinfo?taskID=34693382
