### ISSUE TITLE
Can't dump a module to string when xmd contains a populated list from Python

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#290]
From Python, if a modulemd has an `xmd` that contains a populated list (empty lists work), it can't be dumped to a string.

Here is the reproducer:
```python
import requests
import gi
gi.require_version("Modulemd", "2.0")
from gi.repository import Modulemd

rv = requests.get(
    'https://pagure.io/fm-orchestrator/raw/master/f/tests/staged_data/formatted_testmodule.yaml')
rv.encoding = 'utf-8'
mmd_str = rv.text
mmd = Modulemd.ModuleStream.read_string(mmd_str, True)
mmd = mmd.upgrade(2)

xmd = mmd.get_xmd()
xmd["something"] = ["foo", "bar"]
mmd.set_xmd(xmd)

index = Modulemd.ModuleIndex()
index.add_module_stream(mmd)
index.dump_to_string()
```

The output is:
```
gi.repository.GLib.Error: modulemd-yaml-error-quark: Unhandled variant type: "v" (4)
```

**Comment by sgallagher** [comment]
Scratch-build containing all patches since 2.3.1 for Fedora 29
 https://koji.fedoraproject.org/koji/taskinfo?taskID=34769645

**Comment by sgallagher** [comment]
Previous scratch-build failed because I forgot to push some test files into the patch.

https://koji.fedoraproject.org/koji/taskinfo?taskID=34770448 should work now.
