### ISSUE TITLE
Make Fedora Infra builds

### ISSUE THREAD

**Issue by puiterwijk** [fedora-modularity/libmodulemd#293]
Please make Fedora Infra EPEL7 builds for use in MBS for @mprahl.

SOP on doing this: https://fedora-infra-docs.readthedocs.io/en/latest/sysadmin-guide/sops/infra-repo.html

**Comment by sgallagher** [comment]
I've submitted 2.4.0 as https://koji.fedoraproject.org/koji/taskinfo?taskID=34833267

It should make its way to epel7-infra-stg once the tagging is complete.

@mprahl Can we divide the duties here? If I submit to staging, can you be responsible for doing `koji move epel7-infra-stg epel7-infra NVR` once you confirm it works?

**Comment by mprahl** [comment]
@sgallagher sounds good to me. Are there other services in Fedora Infra that use libmodulemd (e.g. Pungi)? I would want to coordinate with the SMEs of those services before releasing an update.

**Comment by sgallagher** [comment]
@mprahl Pungi is currently still on libmodulemd 1.x (as is DNF), so I think we're fine.

**Comment by sgallagher** [comment]
OK, I pushed private branches `epel-libmodulemd1` and `epel-libmodulemd2` to the libmodulemd dist-git repo in Fedora. Those branches each include a `./build-infra.sh` that will build for the staging tags, so I think I can close this ticket.
