### ISSUE TITLE
RFE: add a way to set koji settings

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-modularity/libmodulemd#296]
I'm thinking about doing RPM:4.15 module which supports dynamic BuildRequires. However, that needs to be turned on in mock config.

It would be very good if I could set it in modulemd and MBS could use it.

@contyk @mprahl @hanzz

**Comment by sgallagher** [comment]
@ignatenkobrain Can you be more explicit about what you need? I don't know what "that needs to be turned on in mock config" means from a technical standpoint.

**Comment by ignatenkobrain** [comment]
@sgallagher I need to set some settings for koji target (`dynamic_buildrequires=True`) which is used by mock.

**Comment by sgallagher** [comment]
@ignatenkobrain And that's not something that can be handled by the `data.buildopts.rpm_macros`, I presume?

Given that this is *specifically* a build-system peculiarity, I'm not sure I'd want to encode this in the formal libmodulemd specification. @mprahl @hanzz could we just define a section in the `xmd` area for such things and have MBS check for it?

e.g.:
```yaml
document: modulemd
version: 2
data:
  ...
  xmd:
    mock:
      options:
        dynamic_buildrequires: True
```

**Comment by mprahl** [comment]
@ignatenkobrain could you please open a ticket for this on the MBS repo?

I think instead of `xmd.mock.options.dynamic_buildrequires`, we can place it in `xmd.mbs_options.dynamic_buildrequires`. We already have a convention for putting advanced build options there. Then MBS can look at the value when appropriate.

**Comment by sgallagher** [comment]
Closing this as we aren't making any changes on this side. @ignatenkobrain please open the MBS version if you haven't already.

**Comment by ignatenkobrain** [comment]
@sgallagher actually @contyk wanted to comment on this one....

**Comment by sgallagher** [comment]
@contyk Do you have something to say here?

**Comment by sgallagher** [comment]
Re-closing this due to lack of response for two months.
