### ISSUE TITLE
Cannot use libmodulemd with libdnf (c++)

### ISSUE THREAD

**Issue by mhatina** [fedora-modularity/libmodulemd#30]
Hello,

I am not able to compile libdnf, when including any header from libmodulemd.

Here is minimal reproducer:
[main.cpp.txt](https://github.com/fedora-modularity/libmodulemd/files/1841483/main.cpp.txt)

Compiling using:
```
$ g++ main.cpp `pkg-config --cflags --libs modulemd`
```

**Comment by sgallagher** [comment]
Ah, the header files are missing `extern C { }` blocks. I'll get an update out ASAP.

**Comment by ignatenkobrain** [comment]
@sgallagher please use `G_BEGIN_DECLS` + `G_END_DECLS`

**Comment by sgallagher** [comment]
@ignatenkobrain I actually DO use those; but it appears G_END_DECLS is missing from one of the headers `#include`d by modulemd.h.

I will fix this.

**Comment by sgallagher** [comment]
I just submitted libmodulemd-1.1.3-2 to updates-testing for all active Fedora releases and EPEL 7.
