### ISSUE TITLE
Add annotations for object properties

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#315]
We have good documentation for the object methods in libmodulemd, but we are entirely missing them for the object properties, which is particularly important for people who are writing code in a bound language such as Python.

For example, I was working with someone yesterday who was unaware that they could get the module stream name by doing `stream.props.stream_name` from Python.

**Comment by mmathesius** [comment]
This issue was resolved by commit b8bcf46.
