### ISSUE TITLE
[Docs] Include object property examples in Python

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#316]
Related to #315, we should provide examples of using object properties in Python, once the properties are visible in the documentation.

**Comment by SunitiJain** [comment]
Is this issue still open? I would like to work on it. 
Thanks

**Comment by mmathesius** [comment]
@SunitiJain 
> Is this issue still open? I would like to work on it.

Yes. Thank you for your interest in contributing-it would be greatly appreciated!

**Comment by OrionStar25** [comment]
@sgallagher I've submitted all the `good-first-issues` as part of GCI (Google Code-In). Do you suggest I add a label to it or let it be?

**Comment by mmathesius** [comment]
Fix by #436.
