### ISSUE TITLE
Make ModulemdErrorEnum into a public enum

### ISSUE THREAD

**Issue by mmathesius** [fedora-modularity/libmodulemd#341]
`ModulemdErrorEnum` is currently defined as part of the private API in `private/modulemd-util.h`. It should be made public (likely in main `modulemd.h`) so it can be used by the python bindings.  For example, if someone catches a `GLib.Error`, they can check whether it's a validation error or something else. See https://pagure.io/pungi/pull-request/1240#request_diff as a specific use case where this would be useful.

**Comment by mmathesius** [comment]
@sgallagher Putting `ModulemdErrorEnum` in the main `modulemd.h` would actually get kind of messy--since it would mean every source file that references one of the `MODULEMD_ERROR_*` enums would have to have `#include "modulemd.h"` added--which seems like a dependency that should be avoided. No existing header file is the right fit to contain it, either.

So, perhaps a new public `modulemd-utils.h`, `modulemd-types.h`, `modulemd-enums.h`, `modulemd-error-types.h`, or similar would be in order. Which file name makes the most sense?

**Comment by sgallagher** [comment]
@mmathesius I think `modulemd-errors.h` probably makes the most sense. 

Also, we should probably move `ModulemdYamlErrorEnum` into the `modulemd-errors.h` as well, since those errors are returned in the `failures` list from the `index.update_from_*()` functions.

**Comment by sgallagher** [comment]
Fixed by https://github.com/fedora-modularity/libmodulemd/pull/346
