### ISSUE TITLE
modulemd-validator: missing man page

### ISSUE THREAD

**Issue by Ionic** [fedora-modularity/libmodulemd#365]
User-visible binaries in `{,/usr}/{,s}bin` should have documentation associated with them, at the very least a man page.

This is currently not the case.

**Comment by sgallagher** [comment]
Agreed, this is lacking. It's low on my priority list, though. The `--help` output is reasonably useful and it's a fairly simple program. But I'll look into adding it when I have spare cycles.

**Comment by OrionStar25** [comment]
Could this be taken up by one of the google code in participants?

**Comment by sgallagher** [comment]
@OrionStar25 Yes, absolutely!
