### ISSUE TITLE
update_from_defaults_directory does not check for conflicting streams

### ISSUE THREAD

**Issue by lubomir** [fedora-modularity/libmodulemd#366]
If I have a directory with two defaults files that are conflicting (same module name, different default stream), this function will load the files and not produce any error even with `strict=True`.

This would be handy in Pungi. There was [a change](https://github.com/fedora-modularity/libmodulemd/commit/3087e4a5c38a331041fec9b6b8f1a372f9ffe64d) to make this error reporting possible, but with this new API for loading defaults it is not usable.

**Comment by sgallagher** [comment]
@lubomir Do you think it makes sense to have the `strict` variable control this or would you prefer if I created a `Modulemd.update_from_defaults_directory_ext()` function with a `strict_default_streams` argument like `Modulemd.ModuleIndexMerger.resolve_ext()` has?

**Comment by lubomir** [comment]
I think just reusing `strict` would be sufficient.

**Comment by sgallagher** [comment]
@lubomir OK, I can do that. Should have something today or tomorrow.

**Comment by lubomir** [comment]
No pressure, I can work around this very easily.

**Comment by sgallagher** [comment]
@lubomir I just pushed the patch for this into all released branches in Fedora: https://bodhi.fedoraproject.org/updates/?like=libmodulemd

Please test and give karma.
