### ISSUE TITLE
[RFE] More lenient defaults merging

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#368]
The current behavior of the defaults merging logic is located at https://fedora-modularity.github.io/libmodulemd/latest/modulemd-2.0-Modulemd.ModuleIndexMerger.html

In particular, this part of the logic: "When merging ModuleIndexes, if two or more indexes contain Defaults for the same module, but different modified values, the one with the highest modified value will be used and the others discarded."

I realized today that this is going to be problematic for EPEL, because it will mean that EPEL will interact negatively with the RHEL defaults. If EPEL provides a defaults object (such as to set default profiles for streams present in EPEL), it may override the RHEL defaults object entirely (or, if RHEL is newer, the EPEL default profiles will be dropped).

I propose to change the merge logic to be such that instead of the `modified` field resulting in it being an override, it should instead act only in the event of conflict resolution. So if there are two objects whose merge would otherwise conflict in one or more places, the one with the higher version for that item would be used, rather than using the entire object.

@contyk @mmathesius Can you give me your opinion on this? It's arguably an incompatible change, but without it we can't have third-party repositories providing defaults at all, which I think is pretty fundamental.

**Comment by contyk** [comment]
Yes, that makes sense to me. +1

**Comment by mmathesius** [comment]
Agreed. (Although it is strictly an incompatible change, it's a new situation that wasn't previously considered.)
