### ISSUE TITLE
Allow to disable gtk-doc building

### ISSUE THREAD

**Issue by tpgxyz** [fedora-modularity/libmodulemd#369]
Can you please allow to disable gtk-doc building in meson_options ? Thanks.

**Comment by sgallagher** [comment]
I can, but would you mind describing your use-case?

**Comment by tpgxyz** [comment]
Dependency bloat, just to build some docs which is not essential to get this package working.
Anyways pulling gtk-doc inside rpm build chroot also pulls many packages required by gtk-doc.
Building documentation should be optional, unless license says different.

**Comment by sgallagher** [comment]
Sure, that's reasonable. I'll get this done for 2.8.1.

**Comment by tpgxyz** [comment]
@sgallagher I've prepared PR
