### ISSUE TITLE
Document migration from  v1 to v2

### ISSUE THREAD

**Issue by KOLANICH** [fedora-modularity/libmodulemd#376]

**Comment by sgallagher** [comment]
I'm not really sure how to document the migration, because they are very different approaches. It's probably best to just read through the [documentation for v2](https://fedora-modularity.github.io/libmodulemd/latest/) which includes quite a few examples.

**Comment by KOLANICH** [comment]
I am neither familiar to v1, nor to v2.  My current goal is to setup building all the necessary packages to make debian packages with libdnf with its python bindings. But it seems that libdnf uses v1 API even though in CMakeLists.txt it requires 2.0 (more precisely, it doesn't builds against the latest git).

**Comment by sgallagher** [comment]
libdnf has v2 on its roadmap: https://bugzilla.redhat.com/show_bug.cgi?id=1693683

If you need to work with v1, the documentation I have on it is at https://fedora-modularity.github.io/libmodulemd/1.8/


Yeah, v2 is a total rewrite. It's not compatible with v1 at all.

**Comment by KOLANICH** [comment]
Thanks for the info. I guess I would have to use the old version untill the migration. Could you also apply #375 to 1 branch?
