### ISSUE TITLE
Implement retry logic in CI tests

### ISSUE THREAD

**Issue by sgallagher** [fedora-modularity/libmodulemd#386]
There are a few places in the CI tests that require external resources (`dnf install` and `docker pull`, mainly). Occasionally one of these hits a network hiccup and fails, causing the test to fail (and all subsequent stages to be canceled).

We should implement a retry mechanism for these calls to make the tests more reliable. It's probably sufficient to try three times before giving up.

**Comment by mmathesius** [comment]
Fix by #434.
