### ISSUE TITLE
Add the ability to set the architectures to build for in the modulemd file

### ISSUE THREAD

**Issue by mprahl** [fedora-modularity/libmodulemd#399]
Currently, there is a way to override the arches per component, but it'd be nice to be able to set the default arches at the module level. In practice, MBS would set these arches on the build tags it creates in Koji.

This should likely be a field under `buildopts`.

**Comment by sgallagher** [comment]
@mprahl Something like this?

```
...
data:
  ...
  buildopts:
    arches: [ x86_64 ]
    ...
```

**Comment by mprahl** [comment]
@sgallagher yes. That looks good to me.

**Comment by sgallagher** [comment]
@mprahl What sort of behavior do you expect if someone sets the `arches` field both in buildopts and for a specific component?

The cases we should consider:

1. Do we allow them to both be used in the same modulemd, or are they mutually-exclusive?
1. If the component set of arches is a proper subset of those in the buildopts, do we just build that component for that subset of arches or for all arches listed in buildopts?
1. If the component set of arches contains some arches not listed in the buildopts, do we build only the intersection of the sets?
1. If the component set of arches is completely disjoint from the set listed in buildopts, how do we proceed?

@contyk Your input would also be valuable here.

**Comment by sgallagher** [comment]
@mmathesius as well

**Comment by mprahl** [comment]
I've stated my opinions inline.

> @mprahl What sort of behavior do you expect if someone sets the `arches` field both in buildopts and for a specific component?
> 
> The cases we should consider:
> 
> 1. Do we allow them to both be used in the same modulemd, or are they mutually-exclusive?

Yes

> 2. If the component set of arches is a proper subset of those in the buildopts, do we just build that component for that subset of arches or for all arches listed in buildopts?

I think we should use the subset.

> 3. If the component set of arches contains some arches not listed in the buildopts, do we build only the intersection of the sets?

I think the modulemd validation should fail.

> 4. If the component set of arches is completely disjoint from the set listed in buildopts, how do we proceed?

I think the modulemd validation should fail.

**Comment by sgallagher** [comment]
@mprahl I agree on all points. I'll proceed with that approach.

**Comment by mmathesius** [comment]
@sgallagher I also agree on all points.

**Comment by sgallagher** [comment]
The plan is to add the `arches` attribute to `data.buildopts` in [`spec.v2.yaml`](https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml) and extend the `Modulemd.Buildopts` object with a set of new methods:

* `modulemd_buildopts_add_arch()`
* `modulemd_buildopts_remove_arch()`
* `modulemd_buildopts_clear_arches()`
* `modulemd_buildopts_get_arches_as_strv()`

Then also extend the `modulemd_module_stream_*_validate()` routine to ensure that the stream is compliant with the policy in this ticket.

Tests of all of these new methods must also accompany the change.
