### ISSUE TITLE
Search ModuleIndex for streams containing particular NEVRA

### ISSUE THREAD

**Issue by kontura** [fedora-modularity/libmodulemd#429]
It should also support fnmatching.

We can provide separated strings of NEVRA as different arguments.
Filters for: name, version, epoch, release, architecture and also the full NEVRA string.

**Comment by sgallagher** [comment]
@kontura 
Is it acceptible to give you just the full nevra string matching for now? We don't actually maintain the split NEVRA in the module metadata, so providing the split lookup would be difficult. Even if you have the components separated already, merging them into a NEVRA format should be a trivial `sprintf()`.

I'm thinking we'd have: `modulemd_module_index.search_rpms_by_nevra(nevra_glob)` as the interface, returning a `GPtrArray` of `ModulemdModuleStream` objects that match the provided NEVRA. Does that seem reasonable to you?
