### ISSUE TITLE
Modulemd: enforce N-E:V-R.A format in artifacts/rpms

### ISSUE THREAD

**Issue by dmach** [fedora-modularity/libmodulemd#46]
The DNF team proposes a change in how libmodulemd handles RPM NEVRAs.
We'd like to always get records in N-E:V-R.A format.
libmodulemd SHOULD fail on reading data in invalid format.
libmodulemd MUST fail on writing data in invalid format.

As part of this, we'd like to enforce '0:' epoch when the epoch is zero or empty in RPM.
In some cases missing epoch can represented as "any epoch", which may result in bad UX.

**Comment by ignatenkobrain** [comment]
technically, missing Epoch means epoch=0. I'm quite hesitant to make this change since it's pointless and just increases size of md.

**Comment by sgallagher** [comment]
@dmach This ticket is asking only for the [data.artifacts.rpms](https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml#L319) list to be in this format and not for [data.api.rpms](https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml#L202) or [data.filter.rpms](https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml#L215), correct?

I *can* make such a change, but currently libmodulemd doesn't validate these strings at all. That information comes from the MBS or Pungi (I forget which) and I only validate that it is a string at the moment. If you want that change to happen, it needs to happen in the build-system first. After that, I can make the parser strict.

**Comment by contyk** [comment]
The summary of the ticket only talks about `data.artifacts.rpms`.

The specification already says that this list includes NEVRAs but I'm also unsure whether such validation belongs in libmodulemd -- I'd much rather see a test for this (and other things) in a compose level test of some kind.

And for the record, it's Pungi that fills this in.

**Comment by sgallagher** [comment]
Ah right, the spec *does* say that it's NEVRA and even has `0:` epoch in its examples. If that's required by the spec, libmodulemd probably should be validating it. That being said, I'd prefer not to land such validation until pungi is producing the correct output or else we're going to cause problems.

**Comment by sgallagher** [comment]
@contyk I assume that it must not be, else I can't really see @dmach filing this ticket.

@dmach, can you show me an example of an artifact that isn't using the epoch notation?
