### ISSUE TITLE
Module Yaml Error 

### ISSUE THREAD

**Issue by megarajan** [fedora-modularity/libmodulemd#471]
Pardon if this is the wrong place to raise this issue.  
Whenever I give any yum command, I get the below Module Yaml errors. My search led me to the libmodulemd , hence asking here.

 yum repolist all
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Last metadata expiration check: 0:01:38 ago on Tue 12 May 2020 10:15:17 AM UTC.
Module yaml error: Document type was unspecified or unknown
Module yaml error: Document type was unspecified or unknown
Module defaults error: Document type was unspecified or unknown
Module defaults error: Document type was unspecified or unknown

**Comment by sgallagher** [comment]
This looks like the problem is with the repository metadata. Is this a public mirror of CentOS? If so, could you show me which one?

**Comment by megarajan** [comment]
thanks for taking a look. 
no this is not seen in a public mirror. this is my private installation of centos8.
I am in particular looking at the "Module yaml errors"
As of now these warnings seem to be harmless, but it would be great if you can give any pointers on how I can debug/triage this warnings or disable them.

**Comment by sgallagher** [comment]
> thanks for taking a look.
> no this is not seen in a public mirror. this is my private installation of centos8.

My guess then is that the tool you used to sync the mirror needs to be updated to ensure that it also pulls in the `<hash>-modulemd.yaml.gz` from the `repodata/` directory. The error you're seeing suggests that the module metadata is missing or corrupt.

> I am in particular looking at the "Module yaml errors"
> As of now these warnings seem to be harmless, but it would be great if you can give any pointers on how I can debug/triage this warnings or disable them.

They probably are NOT harmless; A lot of RHEL 8 depends on modules being available.

**Comment by megarajan** [comment]
thanks. I think the issue is as you noted in the <hash>-modulemd.yaml.gz as you noted which I am looking into.

I believe this can be closed.
