### ISSUE TITLE
Changing master to main causes issues with Yocto builds

### ISSUE THREAD

**Issue by allsey87** [fedora-modularity/libmodulemd#477]
To be clear, I am 100% supportive of the BLM movement, but I am 100% against the renaming the master branches of software to main. This is already causing issues in the Yocto build system and god knows how many other places.

I would like to point out that English is a complicated mess of a language. The word master like many words in English has several meanings, only one of which refer to notion of master and slave (see below).

![image](https://user-images.githubusercontent.com/3796345/85419705-b2ddc900-b572-11ea-95f4-a354fe8e876f.png)

The use of the word master in Git terminology refers to it being the principal or the main copy of a piece of software and has nothing to do with slavery.

**Comment by sgallagher** [comment]
If you are experiencing a specific issue with libmodulemd's change to `main`, please let me know. As of right now, you are not reporting a bug, so I'm closing this ticket.

**Comment by allsey87** [comment]
This is a [recipe from the Yocto repository](https://git.yoctoproject.org/cgit.cgi/poky/plain/meta/recipes-devtools/libmodulemd/libmodulemd_git.bb), a build system that is used to compile complete Linux  systems for millions of embedded devices worldwide.

You have single-handedly broken every single release of Yocto that includes libmodulemd. There are probably 1000s of people looking at the output of the build system right now trying to figure out what went wrong.

**Comment by allsey87** [comment]
Example of the error message:

> ERROR: libmodulemd-native-2.6.0-r0 do_fetch: Fetcher failure: Unable to find revision 7c7f88258491866cdb86d26cadfce37a78f242ec in branch master even from upstream
> ERROR: libmodulemd-native-2.6.0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/fedora-modularity/libmodulemd;protocol=https'. Unable to fetch URL from any source.
> ERROR: Logfile of failure stored in: /home/user/poky-zeus/build/tmp/work/x86_64-linux/libmodulemd-native/2.6.0-r0/temp/log.do_fetch.1215
> ERROR: Task (virtual:native:/home/user/poky-zeus/meta/recipes-devtools/libmodulemd/libmodulemd_git.bb:do_fetch) failed with exit code '1'

**Comment by sgallagher** [comment]
OK, that's a concrete issue and one I can look into. Why does yocto hard-code `master` though? I'm certain libmodulemd isn't the only project to use a default branch with a different name. Or is it just doing that because a previous build came from `master`?

I can recreate the master branch so that revision can be found within it, but I'm not committing to keep the branch in sync with `main`. I'll probably just add a new commit that contains a README.md explaining that the default branch has been changed.

**Comment by sgallagher** [comment]
The `master` branch is restored and is (currently) in sync with the `main` branch. @allsey87 Can you answer my questions above about how Yocto works and whether it depends on the presence of a `master` branch?

**Comment by allsey87** [comment]
Yocto usually points to a certain commit in master for various reasons that
usually come down to compatibility with other software that depends on it.
It is also not unusual for recipes to reference a particular commit from
master and apply patches against it.

Keeping a master branch with the required commits in it would be a
workaround for Yocto, and future releases could then reference the main
branch explicitly in the recipes.

There are, however, probably many other scripts and systems out there that
assume the existence of a master branch. I really do not understand why
anyone would take this cheap marketing stunt seriously. I would argue it
undermines the BLM movement more than it supports it.

**Comment by klauskiwi** [comment]
```
WARNING: libmodulemd-native-2.9.4-r0 do_fetch: Failed to fetch URL git://github.com/fedora-modularity/libmodulemd;protocol=https;branch=main, attempting MIRRORS if available
ERROR: libmodulemd-native-2.9.4-r0 do_fetch: Fetcher failure: Unable to find revision c7254db07b21495fc9bd247c5b17ee20149c05e3 in branch main even from upstream
ERROR: libmodulemd-native-2.9.4-r0 do_fetch: Fetcher failure for URL: 'git://github.com/fedora-modularity/libmodulemd;protocol=https;branch=main'. Unable to fetch URL from any source.
```
Came across this when trying to build yocto gatesgarth-24.0.1, which was confusing since the change from master to main was already in the repo..

Turns out I had an old version of the repository in my builds/downloads directory and this confused git greatly.
```
klausk2@gfw169:/tmp/klausk2/build/downloads/git2/github.com.fedora-modularity.libmodulemd$ git remote show origin
error: refs/pull/478/merge does not point to a valid object!
error: refs/pull/478/merge does not point to a valid object!
* remote origin
  Fetch URL: https://github.com/fedora-modularity/libmodulemd
  Push  URL: https://github.com/fedora-modularity/libmodulemd
  HEAD branch: main
  Remote branches:
    1.x-maint                        tracked
    main                             tracked
<...>
$ git fetch --all --tags
Fetching origin
error: refs/pull/478/merge does not point to a valid object!
error: refs/pull/478/merge does not point to a valid object!
error: refs/pull/478/merge does not point to a valid object!
```
So just documenting here that if anyone is hitting this, make sure you `rm -rf build/downloads/git2/github.com.fedora-modularity.libmodulemd*`
