### ISSUE TITLE
build: add `modulemd_dep`

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-modularity/libmodulemd#54]
By using `declare_dependency()` for ease of bundling libmodulemd..

In theory, should be something like

```meson
modulemd_dep = declare_dependency(
    include_directories : include_directories('.'),
    link_with : modulemd_lib,
)
```

**Comment by ignatenkobrain** [comment]
I would use libmodulemd as a subproject() from my project.

**Comment by sgallagher** [comment]
You are talking about adding something like this to the meson.build file? Would this happen at the top-level or in the modulemd subdir?

I'll definitely do this; I just want to make sure I'm doing it correctly.

**Comment by ignatenkobrain** [comment]
> or in the modulemd subdir?

This.

**Comment by sgallagher** [comment]
@ignatenkobrain please try the PR I just submitted and see if it works for you.
