### ISSUE TITLE
Resolvement of default conflict - investigation/fix

### ISSUE THREAD

**Issue by j-mracek** [fedora-modularity/libmodulemd#548]
Please could you investigate that libmodulemd v1, v2, and v2 with static_contexts is able properly resolve conflicts in defaults. The investigation is critical to allow changes in defaults during life-cycle of distribution.

Requirements:

- defaults for module are modified (stream or profile), but `modified` value will be identical.
-- libmodulemd will report the problem
-- defaults for other modules will be correctly resolved

- defaults for module are modified (stream or profile), but `modified` value will differ
-- libmodulemd will keep defaults according to latest documents
-- defaults for other modules will be correctly resolved

**Comment by sgallagher** [comment]
Please see https://fedora-modularity.github.io/libmodulemd/2.12.0/modulemd-2.0-Modulemd.ModuleIndexMerger.html which should answer all of these questions. If any such questions remain, the documentation should be updated to clarify it.

**Comment by j-mracek** [comment]
@sgallagher What does it mean? Are you sure that it will work or not? Or do you prefer to test it after release by our customers?

**Comment by sgallagher** [comment]
@j-mracek Please see https://github.com/fedora-modularity/libmodulemd/blob/main/modulemd/tests/test-modulemd-merger.c and https://github.com/fedora-modularity/libmodulemd/blob/main/modulemd/tests/ModulemdTests/merger.py

We have a fairly comprehensive set of tests around the implementation as described.

**Comment by j-mracek** [comment]
Thanks, it means that you do not expect any problem, Good to know. Once again thanks for investigation and fast response.
