### ISSUE TITLE
Regex parsing for context in Stream/Packager v2

### ISSUE THREAD

**Issue by mcurlej** [fedora-modularity/libmodulemd#549]
Hi All,

we need to adjust the regex for context parsing. We need to investigate the regex which parses context.  The regex needs to be `a-zA-Z0-9.-_` to accomodate for contex suffixes. Can you take a look?

The specs:
https://github.com/fedora-modularity/libmodulemd/blob/main/yaml_specs/modulemd_stream_v2.yaml#L91

**Comment by sgallagher** [comment]
There is no regex there. See https://github.com/fedora-modularity/libmodulemd/blob/main/modulemd/modulemd-module-stream-v2.c#L1237

You should be able to just add a check for `.`, `-`, and `_` to https://github.com/fedora-modularity/libmodulemd/blob/main/modulemd/modulemd-module-stream-v2.c#L1260

(Also, if 10 characters is insufficient, update MMD_MAXCONTENTLEN).

If you change this parsing, please also update the specification for the stream and packager YAML formats.

**Comment by ppisar** [comment]
I believe the requested change is available now in commit 0132015b5729b6077d49fc5beb2c662a563c6e6d.

**Comment by ppisar** [comment]
The tests added in  #550 does not work on RHEL 8.  #552 should fix them.

**Comment by ppisar** [comment]
This issue was resolved with 0132015b5729b6077d49fc5beb2c662a563c6e6d and 6d02f70dc6d958c1d5743ec9ee8794459e671fd1 commits.
