### ISSUE TITLE
Floaty values need to be converted to strings

### ISSUE THREAD

**Issue by m10k** [fedora-modularity/libmodulemd#586]
Hello,

when parsing YAML files generated by libmodulemd, some parsers (yq for example) will mangle floating point values, stripping trailing zeroes. This problem seems to affect mostly stream names when they are not on the right-hand side of a colon, as shown in the two snippets below.

For example, in the following snippet, the profile for `ant:1.10` is mangled to `ant:1.1`.
```
$ cat <<EOF | yq '.' --yaml-output
---
document: modulemd-defaults
version: 1
data:
  module: ant
  stream: "1.10"
  profiles:
    1.10: [common]
...
EOF
document: modulemd-defaults
version: 1
data:
  module: ant
  stream: '1.10'
  profiles:
    '1.1':
      - common
```

And another example where `perl:5.30` becomes `perl:5.3` (I minimized this one to reduce noise):
```
$ cat <<EOF | yq '.' --yaml-output
data:
  dependencies:
  - buildrequires:
      perl: [5.30]
      perl-DBI: [1.641]
      platform: [el8]
...
EOF
data:
  dependencies:
    - buildrequires:
        perl:
          - 5.3
        perl-DBI:
          - 1.641
        platform:
          - el8
```

I assume that this behavior is not intended, since #499 addressed part of this problem quite a while back. I will attempt to fix this issue and create a pull request. Is that okay?

**Comment by m10k** [comment]
I have created pull request #587

**Comment by ppisar** [comment]
Thanks. The pull request was merged.
