### ISSUE TITLE
Empty profile is parsed as a package with an empty name

### ISSUE THREAD

**Issue by ppisar** [fedora-modularity/libmodulemd#593]
Having this document (empty profiles are legal <https://docs.fedoraproject.org/en-US/modularity/policies/packaging-guidelines/#_profiles>):

~~~~
document: modulemd
version: 2
data:
    name: test
    stream: A
    summary: Test.
    description: >
        Test.
    license:
        module: [ MIT ]
    profiles:
        profileA:
          rpms:
~~~~

reading and writing results into:

~~~~
document: modulemd
version: 2
data:
  name: test
  stream: "A"
  summary: Test.
  description: >
    Test.
  license:
    module:
    - MIT
  profiles:
    profileA:
      rpms:
      -
~~~~

This is a bug on parser side:

~~~~
$ cat /tmp/test.py 
#!/usr/bin/python3
import gi
gi.require_version('Modulemd', '2.0')
from gi.repository import Modulemd

module = Modulemd.read_packager_file('/tmp/out')
print("name={}".format(module.get_module_name()))
profile = module.get_profile('profileA')
print("profile={}".format(profile.get_name()))
packages = profile.get_rpms()
for package in packages:
    print("<{}>".format(package))
[test@fedora-37 libmodulemd-devel]$ GI_TYPELIB_PATH=/tmp/build/modulemd LD_LIBRARY_PATH=/tmp/build/modulemd PYTHONPATH=$PWD python3 /tmp/test.py 
name=test
profile=profileA
<>
~~~~

Possibly all rpms lists are affected.

**Comment by sgallagher** [comment]
Your original document is faulty.

```
  profiles:
    profileA:
      rpms:
      -
```
Literally says that there is one entry under `rpms:` and it's an empty scalar.

What you actually want is:
```
  profiles:
    profileA:
      rpms: []
```
This will give you a zero-length array, which will behave as you expect. The docs may need to clarify this, but the way it's behaving is as expected.

**Comment by ppisar** [comment]
My original document is without the trailing hyphen:

~~~~
  profiles:
    profileA:
      rpms:
~~~~

**Comment by sgallagher** [comment]
That's still incorrect, because we expect a YAML_SEQUENCE_START here and we get nothing. The libyaml is probably just trying to treat the lack of content here as a zero-length scalar, but that's pretty much just trying to avoid aborting on an invalid syntax.
