### ISSUE TITLE
Make libmodulemd buildable on CentOS 7 / RHEL 7 

### ISSUE THREAD

**Issue by dmach** [fedora-modularity/libmodulemd#60]
We'll need libmodulemd built for YUM4 CentOS SIG:
https://wiki.centos.org/SpecialInterestGroup/ConfigManagementSIG/YUM4

The build is also needed for several infrastructure tools as they run on RHEL 7.

We can't build libmodulemd as it is, because RHEL doesn't have python3 and meson.

**Comment by ignatenkobrain** [comment]
RHEL or CentOS? What about EPEL?

**Comment by sgallagher** [comment]
@dmach We really do need an answer here. Is there some reason that the EPEL 7 version is insufficient? Because changing build-systems entirely is going to be quite unpleasant.

**Comment by dmach** [comment]
We'll need libmodulemd for both:
- YUM4 CentOS SIG
- RHEL 7

I don't think that any repo that is part of RHEL subscription can rely on EPEL.

**Comment by sgallagher** [comment]
Your original post said that a CentOS SIG needed it. As I understand it, CentOS variants are allowed to carry new software like EPEL.

If RHEL proper needs it, why can’t RHEL add meson and ninja-build to the “Optional” channel? Is it because of python 3? RHEL 7 should be able to build it with SCL python 3, right?

**Comment by ignatenkobrain** [comment]
Resolution is following: libmodulemd is not going to change its buildsystem.

RHEL's webkit2gtk3 is built using software collections (DTS), so this should not be a problem for RHEL. Given that CentOS has to rebuild RHEL packages, there is also way to use SCLs to build packages.

So nothing to do from libmodulemd side.
