### ISSUE TITLE
zstd compression support

### ISSUE THREAD

**Issue by dralley** [fedora-modularity/libmodulemd#606]
Currently DNF supports zstd compression for all other metadata, and this support is (IIRC) enabled on RHEL 8.2+

Createrepo_c is adding support so it is conceivable that it will be used more commonly soon: https://github.com/rpm-software-management/createrepo_c/pull/345

I intend to promote its use in Fedora once that support is stabilized, as I've found it does a significantly better job with RPM metadata than Gzip / Zlib and is generally much faster to compress than Xz / Lzma.

**Comment by ppisar** [comment]
Adding new compression formats into createrepo_c and librepo (used by DNF) is the right place.

Extending libmodulemd to support new compression formats is not good. In my opinion adding a compression support into libmodulemd was a mistake. Applications should compress and decompress the YAML files as the like and only pass a raw YAML into libmoduemd. I actually plan to deprecate the compression support from libmodulemd.

If you agree, I will close this libmodulemd issue as there is nothing to do in libmodulemd.

**Comment by dralley** [comment]
Ack

**Comment by dralley** [comment]
@ppisar I do not see where in librepo compression types are handled?  Are they handled there at all?

**Comment by ppisar** [comment]
I haven't looked yet at librepo. But there or somewhere else must be something because primary.xml is also compressed.

**Comment by kontura** [comment]
It is handled by `libsolv`.

**Comment by ppisar** [comment]
That's a terrible design. I'm working on an XML representation of module metadata and I do not want to duplicate the handling of compression. Because there is no compression declaration in repomd.xml, the consumers have to wild-guess and that makes the implementation prone to various attacks. Having the same functionality in libsolv, libmodulemd, and now in libmodulexd (my working name for the XML handler) is suboptimal.

In the light of the news I will accept extending libmodulemd for zstd, however I'd rather see separating the decompression into librepo or a yet another library. Or can libsolv decompress an arbitrary file from a YUM repository and return its raw representation?

**Comment by dralley** [comment]
@ppisar It sounds like what you want is a single library for all handling of RPM repository metadata.

**Comment by ppisar** [comment]
Yes, and that library should be librepo.

**Comment by kontura** [comment]
> Or can libsolv decompress an arbitrary file from a YUM repository and return its raw representation?

I think it can (de)compress an arbitrary file: https://github.com/openSUSE/libsolv/blob/master/doc/libsolv-bindings.txt#file-management

 `libdnf` even has a wrapper: https://github.com/rpm-software-management/libdnf/blob/dnf-4-master/libdnf/utils/CompressedFile.cpp

**Comment by ppisar** [comment]
I've prepared a support for Zstandard in libmodulemd. The library supports a detection of the compressed format. One of the detection method is by a file name extension. Therefore I'd like to know which extension will crearerepo_c produce? Zstandard standard dictates ".zst", however this createrepo_c pull request <https://github.com/rpm-software-management/createrepo_c/pull/345> supports both ".zst" and ".zstd".

Which extension will be used in YUM repositories?

**Comment by kontura** [comment]
I have updated the createrepo_c PR to recognize just `zst`. :+1:
