### ISSUE TITLE
modulemd_defaults_dumps () Adds fields which where not initially present on the yaml document.

### ISSUE THREAD

**Issue by ipanova** [fedora-modularity/libmodulemd#75]
In [1]: import gi

In [2]: gi.require_version('Modulemd', '1.0')

```
In [3]: from gi.repository import Modulemd

In [4]: x = '/home/ipanova/Downloads/fcb39b9a0b045c35442f1ab05dfd230148b4662fe1ab6ad7cd3e9722ffce8b84-modules.yaml'

In [5]: modules = Modulemd.objects_from_file(x)

In [6]: modules
Out[6]: 
[<Modulemd.Module object at 0x7fb68a5dd2d0 (ModulemdModule at 0x5645864fb000)>,
 <Modulemd.Module object at 0x7fb689cc8d70 (ModulemdModule at 0x5645864fb0f0)>,
 <Modulemd.Module object at 0x7fb689cc8d20 (ModulemdModule at 0x5645864fb1e0)>,
 <Modulemd.Module object at 0x7fb689cc8cd0 (ModulemdModule at 0x5645864fb2d0)>,
 <Modulemd.Module object at 0x7fb689cc8c80 (ModulemdModule at 0x5645864fb3c0)>,
 <Modulemd.Defaults object at 0x7fb689cc8be0 (ModulemdDefaults at 0x564586493280)>,
 <Modulemd.Defaults object at 0x7fb689cc8aa0 (ModulemdDefaults at 0x5645864932c0)>,
 <Modulemd.Defaults object at 0x7fb689cc8a50 (ModulemdDefaults at 0x564586493300)>]

In [7]: defaults = modules[-1]

In [8]: defaults
Out[8]: <Modulemd.Defaults object at 0x7fb689cc8a50 (ModulemdDefaults at 0x564586493300)>

In [9]: defaults.dumps()
Out[9]: '---\ndocument: modulemd-defaults\nversion: 1\ndata:\n  module: django\n  profiles:\n    1.6: [default]\n  intents: {}\n...\n'
```
Meanwhile in the downloaded modules.yaml file the defaults for django look like:

```
---
document: modulemd-defaults
version: 1
data:
  module: django
  profiles:
    1.6: [default]
...
```

Version : libmodulemd-1.5.2-1.fc28.x86_64
NOTE: Intents where NOT present in the original yaml document

Same behaviours is noticed with modulemd_defaults_dump ()

**Comment by ipanova** [comment]
Modulemd.dump() and dumps suffers from same https://sgallagh.fedorapeople.org/docs/libmodulemd/1.5/modulemd-1.0-modulemd.html#modulemd-dump

**Comment by ignatenkobrain** [comment]
Probably it's better to just open one issue which lists all fields which modulemd adds? ;)

**Comment by ipanova** [comment]
probably. feel free to close as dup if that makes your process better.
i opened these are as separate since i do not know if the root cause is same or different.

**Comment by sgallagher** [comment]
Thanks for the report. Yeah, I forgot to make a check for empty content and suppress the fields.

(Also, thanks for reminding me that I need to publish the 1.6.x API docs as well)

I'll close the other issue, please list any that you discover in this one so I can get them all fixed up in one go.

**Comment by ipanova** [comment]
@sgallagher thanks!

**Comment by sgallagher** [comment]
@ipanova So is the list just the intents and buildopts, or are there others?

**Comment by ipanova** [comment]
yes, have not spotted any other discrepancies so far @sgallagher

**Comment by sgallagher** [comment]
@ipanova I've release 1.6.1 with these fixes. Thanks for the report!
