### ISSUE TITLE
implement "buildonly" for components/rpms

### ISSUE THREAD

**Issue by ignatenkobrain** [fedora-modularity/libmodulemd#95]
For instance, in rust ecosystem we just want to pull components for the buildroot. Yes, you can use `filter`, but since that doesn't support globs/regex, it would be to complex to list 2-30 rpms per component.

**Comment by contyk** [comment]
This also makes sense to me. MBS could also translate this into `filter` for easier debugging later.

This will need an epic.

**Comment by ignatenkobrain** [comment]
any chance to get this prioritized?

https://src.fedoraproject.org/modules/stratis/blob/1/f/stratis.yaml#_31

my filter list is taking 368 lines... and it's just one module

**Comment by sgallagher** [comment]
@ignatenkobrain I agree that this makes sense, but it's also non-trivial to implement. I can add the field to libmodulemd easily-enough, but MBS will also need to be updated to convert the artifacts produced by the component into the filter list.

**Comment by ignatenkobrain** [comment]
I think we've pretty much agreed today on F2F meeting that libmodulemd will just add field and MBS will have to find all artifacts built by component and translate it to the filter list.

**Comment by sgallagher** [comment]
Yes, during the recent Modularity Hackfest, this was discussed. I think what we will want to do is add a new optional attribute to the `data.components.rpms` section like:
```
components:
  rpms:
    rust-bar:
      rationale: Needed for frobbing
      ref: 26ca0c0
      buildonly: True
```

The `buildonly` attribute would default to `False` if unspecified. The expected behavior on the build-system side would be to identify any subpackages produced by `buildonly: True` components and automatically add them to the `data.filter` section for the output.

**Comment by ignatenkobrain** [comment]
`true` should be lower case as per yaml's boolean type.

**Comment by sgallagher** [comment]
Sorry, was writing some python and it bled through. I'll edit the above message to correct that.

**Comment by contyk** [comment]
+1 to the proposal.

**Comment by sgallagher** [comment]
OK, this looks like it's accepted, so I'll add this to libmodulemd 2.2.0
